const STATUS_BADGE = {
  draft: "status-badge-draft",
  published: "status-badge-active",
  pending_review: "status-badge-pending",
};

function getStatusBadgeClass(status) {
  return STATUS_BADGE[status] || "status-badge-draft";
}

export default function ContentLibraryCard({ item, onClick }) {
  return (
    <button
      type="button"
      onClick={() => onClick?.(item)}
      className="text-left w-full bg-[rgba(23,27,40,0.5)] border border-white/5 rounded-xl p-4 hover:border-green-500/30 hover:bg-[rgba(23,27,40,0.8)] transition-colors cursor-pointer"
      data-testid={`content-${item.id}`}
    >
      <div className="flex items-start justify-between gap-3 mb-3">
        <div className="flex-1 min-w-0">
          <h4 className="text-base font-semibold text-white mb-2 truncate">{item.title}</h4>
          <div className="flex flex-wrap items-center gap-2">
            <span className="content-badge bg-blue-500/15 text-blue-300 border border-blue-500/20">
              {item.content_type}
            </span>
            {item.platform && (
              <span className="content-badge bg-purple-500/15 text-purple-300 border border-purple-500/20">
                {item.platform}
              </span>
            )}
            <span className={`content-badge ${getStatusBadgeClass(item.status)}`}>
              {item.status}
            </span>
          </div>
        </div>
      </div>
      <p className="text-sm text-gray-400 line-clamp-2">{item.body}</p>
      <div className="mt-3 pt-3 flex items-center justify-between text-xs text-gray-500 border-t border-white/5">
        <span>Generated by {item.generated_by}</span>
        <span className="text-green-400 group-hover:underline">Click to read full →</span>
      </div>
    </button>
  );
}
