const STATUS_BADGE = {
  draft: "status-badge-draft",
  published: "status-badge-active",
  pending_review: "status-badge-pending",
};

function getStatusBadgeClass(status) {
  return STATUS_BADGE[status] || "status-badge-draft";
}

export default function ContentLibraryCard({ item }) {
  return (
    <div
      className="p-4 border border-gray-200 rounded-lg hover:shadow-md transition-shadow"
      data-testid={`content-${item.id}`}
    >
      <div className="flex items-start justify-between mb-3">
        <div className="flex-1">
          <h4 className="text-lg font-semibold text-gray-900 mb-1">{item.title}</h4>
          <div className="flex items-center gap-2">
            <span className="content-badge bg-blue-100 text-blue-700">{item.content_type}</span>
            {item.platform && (
              <span className="content-badge bg-purple-100 text-purple-700">{item.platform}</span>
            )}
            <span className={`content-badge ${getStatusBadgeClass(item.status)}`}>
              {item.status}
            </span>
          </div>
        </div>
      </div>
      <p className="text-sm text-gray-600 line-clamp-2">{item.body}</p>
      <div className="mt-3 flex items-center justify-between text-xs text-gray-500">
        <span>Generated by {item.generated_by}</span>
        <span>{new Date(item.created_at).toLocaleDateString()}</span>
      </div>
    </div>
  );
}
