import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { useState, useMemo } from "react";
import { Sparkles, Calendar } from "lucide-react";
import { api } from "../lib/api";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { toast } from "sonner";
import IdeaCard from "../components/IdeaCard";
import ConnectorCard from "../components/ConnectorCard";
import CreateIdeaDialog from "../components/CreateIdeaDialog";

const studioAPI = {
  getIdeas: () => api.get("/studio/ideas/"),
  createIdea: (data) => api.post("/studio/ideas/", data),
  generateScript: (ideaId) => api.post(`/studio/ideas/${ideaId}/script`),
  getConnectors: () => api.get("/studio/connectors/"),
  getScheduled: () => api.get("/studio/schedule/"),
};

const INITIAL_FORM = { title: "", description: "", topic: "", target_platforms: [] };

function CostComplianceStats({ ideasCount, freeCount, manualCount, blockedCount }) {
  const stats = [
    { label: "TOTAL IDEAS", value: ideasCount, color: "text-white", note: null },
    { label: "FREE CONNECTORS", value: freeCount, color: "text-green-400", note: "$0/month" },
    { label: "MANUAL EXPORT", value: manualCount, color: "text-yellow-400", note: "awaiting API setup" },
    { label: "PAID BLOCKED", value: blockedCount, color: "text-red-400", note: "Cost Guard active" },
  ];

  return (
    <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
      {stats.map((stat) => (
        <div key={stat.label} className="metric-card-enterprise">
          <div className="text-gray-400 text-sm mb-2">{stat.label}</div>
          <div className={`text-3xl font-bold ${stat.color}`}>{stat.value}</div>
          {stat.note && <div className="text-xs text-gray-400 mt-1">{stat.note}</div>}
        </div>
      ))}
    </div>
  );
}

function IdeasEmptyState() {
  return (
    <div className="enterprise-card text-center py-12">
      <Sparkles className="w-12 h-12 text-gray-600 mx-auto mb-4" />
      <p className="text-gray-400">No content ideas yet</p>
      <p className="text-gray-500 text-sm mt-1">Create your first idea to start the pipeline</p>
    </div>
  );
}

function ScheduledEmptyState() {
  return (
    <div className="enterprise-card text-center py-12">
      <Calendar className="w-12 h-12 text-gray-600 mx-auto mb-4" />
      <p className="text-gray-400">No scheduled posts</p>
    </div>
  );
}

function ScheduledPostItem({ post }) {
  return (
    <div className="enterprise-card flex items-center justify-between">
      <div>
        <div className="text-white font-medium">{post.title || "Untitled"}</div>
        <div className="text-gray-400 text-sm">
          {post.platform} · {post.status}
        </div>
      </div>
      <div className="text-gray-400 text-xs">
        {new Date(post.scheduled_time).toLocaleString()}
      </div>
    </div>
  );
}

export default function ContentStudio() {
  const queryClient = useQueryClient();
  const [ideaDialogOpen, setIdeaDialogOpen] = useState(false);
  const [formData, setFormData] = useState(INITIAL_FORM);

  const { data: ideas = [] } = useQuery({
    queryKey: ["studioIdeas"],
    queryFn: () => studioAPI.getIdeas().then((res) => res.data),
  });

  const { data: connectors = [] } = useQuery({
    queryKey: ["studioConnectors"],
    queryFn: () => studioAPI.getConnectors().then((res) => res.data),
  });

  const { data: scheduled = [] } = useQuery({
    queryKey: ["studioScheduled"],
    queryFn: () => studioAPI.getScheduled().then((res) => res.data),
  });

  const createIdeaMutation = useMutation({
    mutationFn: studioAPI.createIdea,
    onSuccess: () => {
      queryClient.invalidateQueries(["studioIdeas"]);
      toast.success("Idea created!");
      setIdeaDialogOpen(false);
      setFormData(INITIAL_FORM);
    },
    onError: (e) => toast.error(`Failed: ${e.message}`),
  });

  const generateScriptMutation = useMutation({
    mutationFn: studioAPI.generateScript,
    onSuccess: () => {
      queryClient.invalidateQueries(["studioIdeas"]);
      toast.success("Script generated by AI!");
    },
    onError: (e) => toast.error(`Failed: ${e.message}`),
  });

  const connectorCounts = useMemo(() => ({
    free: connectors.filter((c) => c.cost_class.startsWith("free")).length,
    manual: connectors.filter((c) => c.cost_class === "manual_free").length,
    blocked: connectors.filter((c) => c.cost_class === "paid_blocked").length,
  }), [connectors]);

  const handleSubmit = (e) => {
    e.preventDefault();
    createIdeaMutation.mutate(formData);
  };

  return (
    <div className="p-6 space-y-6" data-testid="content-studio-page">
      <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4">
        <div>
          <h1 className="text-3xl font-bold text-white mb-1" style={{ fontFamily: 'Space Grotesk' }}>
            Content Factory
          </h1>
          <p className="text-gray-400 text-sm">
            CapCut-style production · Zero-cost · {connectors.length} platforms configured
          </p>
        </div>
        <CreateIdeaDialog
          open={ideaDialogOpen}
          onOpenChange={setIdeaDialogOpen}
          formData={formData}
          setFormData={setFormData}
          onSubmit={handleSubmit}
        />
      </div>

      <CostComplianceStats
        ideasCount={ideas.length}
        freeCount={connectorCounts.free}
        manualCount={connectorCounts.manual}
        blockedCount={connectorCounts.blocked}
      />

      <Tabs defaultValue="ideas" className="w-full">
        <TabsList className="bg-gray-900 border border-gray-800">
          <TabsTrigger value="ideas" data-testid="tab-ideas">Ideas ({ideas.length})</TabsTrigger>
          <TabsTrigger value="connectors" data-testid="tab-connectors">Connectors ({connectors.length})</TabsTrigger>
          <TabsTrigger value="scheduled" data-testid="tab-scheduled">Scheduled ({scheduled.length})</TabsTrigger>
        </TabsList>

        <TabsContent value="ideas" className="mt-6">
          {ideas.length === 0 ? (
            <IdeasEmptyState />
          ) : (
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
              {ideas.map((idea) => (
                <IdeaCard
                  key={idea.id}
                  idea={idea}
                  onGenerateScript={(id) => generateScriptMutation.mutate(id)}
                />
              ))}
            </div>
          )}
        </TabsContent>

        <TabsContent value="connectors" className="mt-6">
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {connectors.map((connector) => (
              <ConnectorCard key={connector.id} connector={connector} />
            ))}
          </div>
        </TabsContent>

        <TabsContent value="scheduled" className="mt-6">
          {scheduled.length === 0 ? (
            <ScheduledEmptyState />
          ) : (
            <div className="space-y-3">
              {scheduled.map((post) => (
                <ScheduledPostItem key={post.id} post={post} />
              ))}
            </div>
          )}
        </TabsContent>
      </Tabs>
    </div>
  );
}
